# Generated by Django 5.1.1 on 2024-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('url', models.URLField()),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('file_path', models.FilePathField()),
            ],
            options={
                'unique_together': {('url', 'start_time', 'stop_time')},
            },
        ),
    ]
