# Generated by Django 5.1.1 on 2024-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard_clip_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundclip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending'),
        ),
    ]
