# Generated by Django 5.1.1 on 2024-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard_clip_generator', '0002_alter_soundclip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundclip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
