# Generated by Django 5.1.1 on 2024-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard_clip_generator', '0003_alter_soundclip_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundclip',
            name='file_path',
        ),
        migrations.AddField(
            model_name='soundclip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
