# Generated by Django 5.1.1 on 2024-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard_clip_generator', '0004_remove_soundclip_file_path_soundclip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundclip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='clips'),
        ),
    ]
