# Generated by Django 5.1.1 on 2024-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalores', '0002_alter_discorduser_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='discord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
