# Generated by Django 5.1.1 on 2024-11-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalores', '0003_alter_discorduser_discord_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='discord_email',
        ),
    ]
