name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push Docker images
      env:
        TAG: ${{ github.ref_name }}
      run: |
        docker build -t ghcr.io/neverw8/mandalores-django:${TAG} .
        docker push ghcr.io/neverw8/mandalores-django:${TAG}
        docker build -t ghcr.io/neverw8/mandalores-nginx:${TAG} -f nginx.Dockerfile .
        docker push ghcr.io/neverw8/mandalores-nginx:${TAG}
        docker build -t ghcr.io/neverw8/mandalores-tasks:${TAG} -f tasks.Dockerfile .
        docker push ghcr.io/neverw8/mandalores-tasks:${TAG}

    - name: Log out of GitHub Container Registry
      run: docker logout ghcr.io

